### PR TITLE
Search

### PR DESCRIPTION
**Pull request by Drapegnik**
* add choose image dialog
* speed up search
* run in new thread
* store FeaturesMap into `Storage`

### CODE REVIEW

**Comment by UladBohdan** [comment]
LGTM
(more or less)
I would merge.

on **career dataset** (128 images), ubuntu 16.04, 2gb ram, 2 cores:

_performing search for image from dataset_
`I0502 00:53:06.633086  9472 featuresx.cpp:56] It took 4.14216 seconds to extract features`
`I0502 00:53:06.643559  9472 project.cpp:64] Successfully extract 13631 features`
`I0502 00:53:06.643610  9472 featuresx.cpp:105] Feature map not loaded into memory.`
`I0502 00:53:12.140470  9472 featuresx.cpp:122] It took 1.76195 seconds to build map`
`I0502 00:54:09.822998  9472 project.cpp:105] It took 56.6911 seconds to search`
`I0502 00:54:09.829257  9472 project.cpp:106] Match 3902/97959 tracks`

screen shot 2017-05-02 at 12 55 25 am

_performing search for image which has nothing in common with dataset_
`I0502 00:59:48.819464 10850 featuresx.cpp:56] It took 0.712403 seconds to extract features`
`I0502 00:59:48.820443 10850 project.cpp:64] Successfully extract 2337 features`
`I0502 00:59:48.820471 10850 featuresx.cpp:105] Feature map not loaded into memory.`
`I0502 00:59:54.303714 10850 featuresx.cpp:122] It took 1.91179 seconds to build map`
`I0502 01:00:20.560139 10850 project.cpp:105] It took 24.8514 seconds to search`
`I0502 01:00:20.562360 10850 project.cpp:106] Match 66/97959 tracks`
Q: were these 66 tracks rendered? that's not possible to notice with my eyes but, as I see, these 66 tracks must be completely ignored.

on **reduced career dataset** (18 images), ubuntu 16.04, 2gb ram, 2 cores

_performing search for image from dataset_
`I0502 01:05:37.880195 12070 featuresx.cpp:56] It took 3.05382 seconds to extract features`
`I0502 01:05:37.885540 12070 project.cpp:64] Successfully extract 10242 features`
`I0502 01:05:37.885596 12070 featuresx.cpp:105] Feature map not loaded into memory.`
`I0502 01:05:38.803732 12070 featuresx.cpp:122] It took 0.284042 seconds to build map`
`I0502 01:05:47.215920 12070 project.cpp:105] It took 8.31322 seconds to search`
`I0502 01:05:47.216045 12070 project.cpp:106] Match 5535/17845 tracks`

screen shot 2017-05-02 at 1 08 16 am

_performing search for image from large career dataset_
`I0502 01:10:28.551676 12962 featuresx.cpp:56] It took 3.18046 seconds to extract features`
`I0502 01:10:28.557016 12962 project.cpp:64] Successfully extract 12741 features`
`I0502 01:10:28.557060 12962 featuresx.cpp:105] Feature map not loaded into memory.`
`I0502 01:10:28.982877 12962 featuresx.cpp:122] It took 0.18498 seconds to build map`
`I0502 01:10:38.347812 12962 project.cpp:105] It took 9.27793 seconds to search`
`I0502 01:10:38.347879 12962 project.cpp:106] Match 708/17845 tracks`
screen shot 2017-05-02 at 1 10 48 am
looks good!

Issues:
* app was killed after I run search twice without relaunching the app. My guess: memory allocating issue.

Feature requests:
* UI: to make it possible to view the image which is currently in search (or already rendered as searched),

**Comment by UladBohdan** [comment]
although it's still slow.
10 seconds for search on model created from 18-images dataset is not good.

**Review by UladBohdan — APPROVED** [review]

**Comment by Drapegnik** [comment]
more **quarry** statistics:

```
Start process /Users/Drapegnik/projects/uiip/data/quarry/images/IMG_1157.JPG
It took 3.29285 seconds to extract features
Successfully extract 10299 features
It took 3.09645 seconds to build map
It took 33.8006 seconds to search
Match 8900/100013 tracks
```

screen shot 2017-05-01 at 00 37 41
screen shot 2017-05-01 at 00 37 36

**Comment by Drapegnik** [comment]
updated.

**Comment by Drapegnik** [comment]
output for search image, that has nothing in common with model:

```
I0502 15:12:11.131788 193777664 project.cpp:64] Successfully extract 1593 features
I0502 15:12:19.835309 193777664 featuresx.cpp:114] It took 3.65533 seconds to build map
I0502 15:12:44.836423 193777664 project.cpp:109] It took 16.8588 seconds to search
I0502 15:12:44.836499 193777664 project.cpp:110] Match 0/100013 tracks
```

**Comment by UladBohdan** [comment]
@Drapegnik can you please explain how's that happened that we have 0 tracks? are you removing them manually?

**Comment by Drapegnik** [comment]
close #12

**Pull request merged**
